# Title, decription, tagline and URL for your site
# Can be used in your theme by calling 'site.title' and so on
title: A Crisis of Enclosure
description: ruminations on the nondescript catastrophe
url: http://crisisofenclosure.com

# Same as the title etc for your site but can instead be
# called by using 'site.owner.name' and so on
owner:
  name: Richard Nisa

exclude: [Gemfile, Gemfile.lock, README.md]
permalink: /:title
paginate: 10
paginate_path: "/blog/page/:num"
